### ISSUE TITLE
Generated package.json does not include transitive NPM dependencies

### ISSUE THREAD

**Issue by jnfeinstein** [mpetuska/npm-publish#5]
See [spring-bank-client](https://github.com/jnfeinstein/spring-bank/blob/main/spring-bank-project/spring-bank-client/build.gradle.kts#L8).  The `package.json` generated when packed by this plugin does not include `npm` dependencies of `ktor-client-core` found [here](https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-core/build.gradle.kts#L21).  

A minimal application to reproduce would be:
```javascript
require('spring-bank-client').io.joel.springbank.client;
```
which currently results in `Error: Cannot find module 'ws'`.

**Comment by mpetuska** [comment]
IR assemblies now have transitive npm dependencies declared in direct kotlin.js dependencies hoisted to generated package.json

**Comment by jnfeinstein** [comment]
@mpetuska confirmed working in 1.1.3.  Very very cool!  Thanks a bunch for the fix.
